sudo: required
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in .env.enc -out .env -d

script:
  - docker-compose -f docker-compose.test.yml up

notifications:
  email: docker@katagena.com
